swagger: '2.0'
info:
  title: Mock
  x-ibm-name: mock
  version: 2.0.0
x-ibm-configuration:
  cors:
    enabled: true
    policy: []
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - map:
          inputs:
            input:
              schema:
                type: object
                properties:
                  type:
                    type: string
                $$title: input
              variable: request.body
          outputs:
            output:
              schema:
                type: object
                properties:
                  status:
                    type: string
                $$title: output
              variable: message.body
              content: application/json
          actions:
            - set: output.status
              from: input.type
              value: '"successa"'
          version: 2.1.0
          title: map
          options:
            mapEmulateV4EmptyJSONObject: false
            mapEmulateV4DefaultRequiredProps: false
            mapEnablePostProcessingJSON: false
            mapReferenceLimit: 1
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /mock
paths:
  /test:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
schemes:
  - https
